### ISSUE TITLE
Error with fastify 3

### ISSUE THREAD

**Issue by johntom** [guivic/fastify-socket.io#83]
Hi,
my plugin fails when I upgradied from fastify 2.6.0 to fastify 3.17.0
'use strict'
const fp = require('fastify-plugin')
module.exports = fp(async (fastify, opts) => {
    fastify.register(require('@guivic/fastify-socket.io'), opts, (error) => console.error(error));
    const io = fastify.io;
    console.log('/pi 001===plugin================fastify io======\n\r')//, fastify.io) // Socket.io instance
    fastify.get('/', (request, reply) => {
      console.log('/n002',(fastify.io)); // Socket.io instance
    });
});
browser reports  http://localhost:8080/socket.io/?EIO=3&transport=polling&t=Ndi21Jn net::ERR_CONNECTION_REFUSED
node 14.17.0
yarn v1.22.5
tested on windows 10 and windows server 2019
TIA

**Comment by lludol** [comment]
@johntom Hello, thanks for the issue. I will check it this week and I will come back to you.

**Comment by lludol** [comment]
@johntom Please upgrade the package it should work now.
